// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package daggercli

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Module       *string                `mapstructure:"module" cty:"module" hcl:"module"`
	File         *string                `mapstructure:"file" cty:"file" hcl:"file"`
	Call         *string                `mapstructure:"call" required:"true" cty:"call" hcl:"call"`
	Args         map[string]interface{} `mapstructure:"args" cty:"args" hcl:"args"`
	Env          map[string]string      `mapstructure:"env" cty:"env" hcl:"env"`
	WorkingDir   *string                `mapstructure:"working_dir" cty:"working_dir" hcl:"working_dir"`
	LogLevel     *string                `mapstructure:"log_level" cty:"log_level" hcl:"log_level"`
	RetryCount   *int                   `mapstructure:"retry_count" cty:"retry_count" hcl:"retry_count"`
	RetryBackoff *string                `mapstructure:"retry_backoff" cty:"retry_backoff" hcl:"retry_backoff"`
	CacheMode    *string                `mapstructure:"cache_mode" cty:"cache_mode" hcl:"cache_mode"`
	CacheKey     *string                `mapstructure:"cache_key" cty:"cache_key" hcl:"cache_key"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"module":        &hcldec.AttrSpec{Name: "module", Type: cty.String, Required: false},
		"file":          &hcldec.AttrSpec{Name: "file", Type: cty.String, Required: false},
		"call":          &hcldec.AttrSpec{Name: "call", Type: cty.String, Required: false},
		"args":          &hcldec.AttrSpec{Name: "args", Type: cty.Map(cty.String), Required: false},
		"env":           &hcldec.AttrSpec{Name: "env", Type: cty.Map(cty.String), Required: false},
		"working_dir":   &hcldec.AttrSpec{Name: "working_dir", Type: cty.String, Required: false},
		"log_level":     &hcldec.AttrSpec{Name: "log_level", Type: cty.String, Required: false},
		"retry_count":   &hcldec.AttrSpec{Name: "retry_count", Type: cty.Number, Required: false},
		"retry_backoff": &hcldec.AttrSpec{Name: "retry_backoff", Type: cty.String, Required: false},
		"cache_mode":    &hcldec.AttrSpec{Name: "cache_mode", Type: cty.String, Required: false},
		"cache_key":     &hcldec.AttrSpec{Name: "cache_key", Type: cty.String, Required: false},
	}
	return s
}
